---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitops-poc-canary-nginx
  namespace: canary-nginx
spec:
  interval: 5m0s
  path: ./flux/poc/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-poc

