---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitops-poc
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./flux/poc/deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-poc
  targetNamespace: default

